asteroid-data-dir: misc
monitor-interval: 10
site-list:
  - site-name: site1
    site-dir: D:\workspace\dev\test\go\asteroid\site1
    include-ext: ['.ps','.px']
    exclude-dir:
      - D:\workspace\dev\test\go\asteroid\site1\exclude1
      - D:\workspace\dev\test\go\asteroid\site1\exclude2
  - site-name: site2
    site-dir: D:\workspace\dev\test\go\asteroid\site2
    include-ext:
      - .ps
      - .px
    exclude-dir:
      - D:\workspace\dev\test\go\asteroid\site2\exclude1
      - D:\workspace\dev\test\go\asteroid\site2\exclude2

telegram:
  api-url: https://api.telegram.org
  token: 123:xxxxx
  chat-id: -123
  enable: true

email:
  host: smtp.gmail.com
  port: 465
  username: xxx@gmail.com
  password: zurjoncjyqboigaq
  enable: true
  email-to:
    - aaa@gmail.com
    - bbb@gmail.com